flags:
  QuickCheck:
    base4point8: false
packages:
- '.'
extra-deps:
- HList-0.3.4.1
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- StateVar-1.1.0.1
- ansi-terminal-0.6.2.3
- async-2.1.0
- bifunctors-4.2.1
- comonad-4.2.7.2
- contravariant-1.3.3
- dimensional-0.13.0.2
- distributive-0.4.4
- doctest-0.10.1
- exceptions-0.8.0.2
- free-4.12.1
- ghc-paths-0.1.0.9
- hashable-1.2.4.0
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- lens-4.4.0.2
- mtl-2.1.3.1
- nats-1
- numtype-1.1
- parallel-3.2.1.0
- prelude-extras-0.4.0.2
- primitive-0.5.4.0
- profunctors-4.4.1
- quickcheck-io-0.1.2
- random-1.1
- reflection-1.5.2.1
- regex-base-0.93.2
- regex-pcre-0.94.4
- semigroupoids-4.3
- semigroups-0.17.0.1
- setenv-0.1.1.3
- split-0.2.3
- stm-2.4.4.1
- syb-0.6
- tagged-0.7.3
- text-1.2.2.0
- tf-random-0.5
- transformers-compat-0.4.0.3
- unordered-containers-0.2.7.0
- vector-0.10.12.3
- void-0.7.1
- zlib-0.5.4.2
resolver: ghc-7.8.4
